### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AmanAnifer** [TiliCollegeaVarten/Main-Platform#1]
A list of features to implement on this platform

- [ ] Roll number login based system for each participant, the answers will sent to the server(on pressing next) and stored in sqlite database with this roll number as the primary key. Roll number should be given to the participant during the exam.
- [ ] (Optional) Store the questions in the server instead of the client, client will request the question each time. This will prevent any participant from snooping around the HTML source and finding all questions.
- [ ] Questions will be randomly ordered for each participant.
- [ ] If somehow the client lost power or crashed, logging in with the same roll no will automatically fill the already submitted question answers.
- [ ] Running/Compiling the user supplied program to test if it works in the server computer.
- [ ] Checking the score after finishing the test
- [ ] (Highly optional) Admin panel to monitor participant's progress
